CREATE TABLE offerte (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    versione BIGINT NOT NULL,
    nome_fornitore VARCHAR(150) NOT NULL,
    nome_offerta VARCHAR(150) NOT NULL,
    tipo_offerta VARCHAR(30) NOT NULL CHECK (tipo_offerta IN ('PREZZO_FISSO','INDICIZZATA_PUN')),
    tipo_tariffa VARCHAR(30) NOT NULL CHECK (tipo_tariffa IN ('MONORARIA','BIORARIA','TRIORARIA')),
    prezzo_f0 NUMERIC(16,8), prezzo_f1 NUMERIC(16,8), prezzo_f23 NUMERIC(16,8), prezzo_f2 NUMERIC(16,8), prezzo_f3 NUMERIC(16,8),
    spread_f0 NUMERIC(16,8), spread_f1 NUMERIC(16,8), spread_f23 NUMERIC(16,8), spread_f2 NUMERIC(16,8), spread_f3 NUMERIC(16,8),
    pcv_annuo NUMERIC(16,8) NOT NULL CHECK (pcv_annuo >= 0),
    attiva BOOLEAN NOT NULL,
    note VARCHAR(2000)
);
CREATE TABLE voci_corrispettivo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offerta_id BIGINT NOT NULL REFERENCES offerte(id),
    tipo VARCHAR(30) NOT NULL CHECK (tipo IN ('ENERGIA','PCV')),
    fascia VARCHAR(10),
    corrispettivo NUMERIC(16,8) NOT NULL CHECK (corrispettivo >= 0),
    indicizzata BOOLEAN NOT NULL,
    CHECK ((tipo='PCV' AND fascia IS NULL AND indicizzata=FALSE) OR (tipo='ENERGIA' AND fascia IN ('F0','F1','F23','F2','F3')))
);
CREATE INDEX idx_voci_offerta ON voci_corrispettivo(offerta_id);
CREATE TABLE bollette (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    versione BIGINT NOT NULL,
    cliente VARCHAR(150) NOT NULL, pod VARCHAR(30) NOT NULL, fornitore VARCHAR(150) NOT NULL,
    potenza_kw NUMERIC(8,4) NOT NULL CHECK (potenza_kw > 0),
    totale_fatturato NUMERIC(12,2) NOT NULL CHECK (totale_fatturato >= 0),
    aliquota_iva NUMERIC(5,4) NOT NULL CHECK (aliquota_iva BETWEEN 0 AND 1),
    altre_partite_imponibili NUMERIC(12,2) NOT NULL,
    altre_partite_esenti NUMERIC(12,2) NOT NULL
);
CREATE TABLE mesi_bolletta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bolletta_id BIGINT NOT NULL REFERENCES bollette(id), mese VARCHAR(7) NOT NULL,
    f1 NUMERIC(14,6) NOT NULL CHECK (f1 >= 0), f2 NUMERIC(14,6) NOT NULL CHECK (f2 >= 0), f3 NUMERIC(14,6) NOT NULL CHECK (f3 >= 0),
    pun_f0 NUMERIC(16,8), pun_f1 NUMERIC(16,8), pun_f23 NUMERIC(16,8), pun_f2 NUMERIC(16,8), pun_f3 NUMERIC(16,8),
    UNIQUE (bolletta_id,mese)
);
CREATE TABLE parametri_gestore (
    id BIGINT PRIMARY KEY CHECK (id=1), versione BIGINT NOT NULL, configurazione TEXT NOT NULL
);
CREATE TABLE confronti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creato_il TIMESTAMP WITH TIME ZONE NOT NULL, snapshot TEXT NOT NULL
);
