CREATE TABLE dati_ufficiali (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 versione BIGINT NOT NULL,
 codice VARCHAR(80) NOT NULL,
 periodo VARCHAR(7) NOT NULL,
 categoria VARCHAR(40) NOT NULL,
 valore_ufficiale NUMERIC(20,8),
 valore_manuale NUMERIC(20,8),
 fonte VARCHAR(100) NOT NULL,
 url VARCHAR(1000) NOT NULL,
 pubblicato_il DATE,
 acquisito_il TIMESTAMP WITH TIME ZONE NOT NULL,
 UNIQUE(codice,periodo,categoria)
);
CREATE TABLE revisioni_fonti (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 dato_id BIGINT NOT NULL REFERENCES dati_ufficiali(id),
 creato_il TIMESTAMP WITH TIME ZONE NOT NULL,
 motivo VARCHAR(500) NOT NULL,
 contenuto TEXT NOT NULL
);
CREATE TABLE sincronizzazioni_fonti (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 creato_il TIMESTAMP WITH TIME ZONE NOT NULL,
 fonte VARCHAR(100) NOT NULL,
 successo BOOLEAN NOT NULL,
 messaggio VARCHAR(500) NOT NULL
);
CREATE INDEX idx_fonti_periodo_categoria ON dati_ufficiali(periodo,categoria);
CREATE INDEX idx_revisioni_dato ON revisioni_fonti(dato_id,id);
