CREATE TABLE business_profili (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 versione BIGINT NOT NULL,
 configurazione TEXT NOT NULL
);
CREATE TABLE business_revisioni_profili (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 profilo_id BIGINT NOT NULL REFERENCES business_profili(id),
 versione BIGINT NOT NULL,
 modificato_il TIMESTAMP WITH TIME ZONE NOT NULL,
 configurazione TEXT NOT NULL,
 UNIQUE(profilo_id, versione)
);
CREATE TABLE business_simulazioni (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 creata_il TIMESTAMP WITH TIME ZONE NOT NULL,
 ragione_sociale VARCHAR(150) NOT NULL,
 dal VARCHAR(7) NOT NULL,
 al VARCHAR(7) NOT NULL,
 totale NUMERIC(30,2) NOT NULL,
 risparmio NUMERIC(30,2) NOT NULL,
 bozza BOOLEAN NOT NULL,
 snapshot TEXT NOT NULL
);
CREATE INDEX idx_business_simulazioni_data ON business_simulazioni(creata_il,id);
